name: Cherry-Pick to Release

on:
  pull_request:
    types:
      - labeled
permissions:
  contents: write

jobs:
  cherry-pick:
    if: ${{ contains(github.event.label.name, 'released-') && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dev branch
        uses: actions/checkout@v3
        with:
          ref: dev
          fetch-depth: 0  # Fetch all history so we can cherry-pick

      - uses: actions/checkout@v3
      - uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        id: cherry-pick
        with:
          branch: ${{ github.event.label.name }}
          force: true
      - run: |
            echo "${{ steps.cherry-pick }}"
            echo "${{ steps.cherry-pick.outputs }}" 
            echo "${{ toJSON(steps.cherry-pick.outputs) }}"
